---

- hosts: tag_group_name_ZookeeperServers
  user: ubuntu
  become: true
  become_method: sudo
  roles:
    - {
        role: ansible-java,
        when: accept_oracle_licence
      }
    - {
        role: ansible-zookeeper,
        zookeeper_version: 3.4.6
      }
- hosts: tag_group_name_KafkaServers
  user: ubuntu
  become: true
  become_method: sudo
  roles:
    - {
        role: ansible-java,
        when: accept_oracle_licence
      }
    - {
        role: ansible-kafka
      }
