
- name: add add-apt-repostory
  apt: pkg=software-properties-common state=present update_cache=yes
  sudo: yes

- name: add add-apt-repostory
  apt: pkg=python-software-properties state=present update_cache=yes
  sudo: yes
  when: ansible_distribution_release == "precise"
- name: Add apt repository
  apt_repository:
      repo: 'ppa:webupd8team/java'
      state: present
      update_cache: yes

- name: auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  sudo: yes

- name: install java8
  shell: apt-get install -y oracle-java8-installer ca-certificates
  sudo: yes

- name: Set JAVA_HOME
  lineinfile: dest=/etc/environment state=present regexp='^JAVA_HOME' >
     line='JAVA_HOME=/opt/jre1.8.0_51/bin'
